services:
    db:
        image: postgres:14.17
        container_name: postgres-container
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: instacart
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 10
        ports:
          - 5432:5432
        networks:
            - db
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  db:
    driver: bridge

volumes:
  pgdata: